Simple implementation for VK_EXT_mesh_shader supporting
KhronosGroup/SPIRV-Reflect pull request #166
Opened 2023-01-27 13:52 UTC by Chaphlagical

Adding support for `VK_EXT_mesh_shader`

2023-01-27 13:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SPIRV-Reflect?pullRequest=166) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SPIRV-Reflect?pullRequest=166) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SPIRV-Reflect?pullRequest=166) it.</sub>

2023-01-30 21:26 UTC, cassiebeckley requested changes
Can you add a test for this?

2023-01-30 21:26 UTC, cassiebeckley commented on include/spirv/unified1/spirv.h
> +	SpvExecutionModelTaskEXT = 5364,
nit: use spaces instead of tabs

2023-01-31 10:35 UTC, Chaphlagical commented
> Thanks for the contribution! Looks good, but can you add a test for this?

Done.

2023-02-01 02:19 UTC, cassiebeckley requested changes
Thanks! Just one more fix needed I think

2023-02-01 02:19 UTC, cassiebeckley commented on tests/mesh_shader_ext/mesh_shader_ext.task.hlsl.spv.yaml
> +  spirv_execution_model: 5364 # ???
Handle this as well

2023-02-01 05:18 UTC, Chaphlagical commented on tests/mesh_shader_ext/mesh_shader_ext.mesh.hlsl.spv.yaml
> +  spirv_execution_model: 5365 # ???
OK. It's done.

2023-02-01 08:50 UTC, merged