Check return values from FindNode for null pointers
KhronosGroup/SPIRV-Reflect pull request #228
Opened 2023-10-10 20:51 UTC by cassiebeckley

Fixes #227

2023-10-10 22:08 UTC, chaoticbob requested changes
Looks good overall, just one small change.

2023-10-10 22:50 UTC, spencer-lunarg commented on tests/issues/227/null_node.spv
this is not a valid SPIR-V if using `spirv-val`

seems it has `GLSL.std.453` 

after I see 

`%21 = OpAccessChain %20 %_ %19`

2023-10-11 18:37 UTC, cassiebeckley commented on tests/issues/227/null_node.spv
Yeah, this is invalid, I included it specifically as a regression test since it triggers the null pointer dereference. I suspect any SPIR-V that triggers the error will be invalid, since it requires a reference to a node that doesn't exist.

This SPIR-V file is the one that was included in the original report of this issue; I suspect the reporter generated it using a fuzzer. I can try to clean it up more if you think that would be better.

I mention the issues with this file in `README.md`.

2023-10-11 18:38 UTC, cassiebeckley commented
> Looks good overall, just one small change.

@chaoticbob what did you want me to change? I don't think it's showing up for me.

2023-10-11 21:14 UTC, chaoticbob commented
> > Looks good overall, just one small change.
> 
> @chaoticbob what did you want me to change? I don't think it's showing up for me.

One of the comments was to add parens around the right hand side of a logical expressions.

2023-10-11 22:01 UTC, cassiebeckley commented
Okay, fixed that. Anything else?

2023-10-11 22:30 UTC, chaoticbob approved these changes
LGTM

2023-10-11 23:19 UTC, spencer-lunarg commented on tests/issues/227/null_node.spv
That is fair

2023-10-11 23:20 UTC, spencer-lunarg approved these changes

2023-10-12 18:24 UTC, merged